graphql:
  servlet:
    exception-handlers-enabled: true
  playground:
    tabs:
      - name: Item Category sample query
        query: classpath:playground/itemCategory.graphql
        variables: classpath:playground/itemCategoryVariables.json
      - name: User query
        query: classpath:playground/user.graphql
        variables: classpath:playground/userVariables.json
      - name: Book query
        query: classpath:playground/book.graphql
        variables: classpath:playground/bookVariables.json
      - name: Exam query
        query: classpath:playground/exam.graphql
        variables: classpath:playground/examVariables.json

spring:
  datasource:
    platform: POSTGRESQL
    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://cupcakelearning.cyqsklq9p761.ap-southeast-1.rds.amazonaws.com:5432/ccl
#    username: cupcakelearning
#    password: cupcakelearning
    url: jdbc:postgresql:ccl
    username: postgres
    password: postgres
  user-datasource:
    platform: POSTGRESQL
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql:auth
    username: postgres
    password: postgres
  exam-book-datasource:
    platform: POSTGRESQL
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql:exam_book
    username: postgres
    password: postgres
  jpa:
    generate-ddl: true
    hibernate.ddl-auto: create