graphql:
  servlet:
    exception-handlers-enabled: true
  playground:
    tabs:
      - name: Bank account sample query
        query: classpath:playground/itemCategory.graphql
        variables: classpath:playground/itemCategoryVariables.json

spring:
  datasource:
    platform: POSTGRESQL
    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://cupcakelearning.cyqsklq9p761.ap-southeast-1.rds.amazonaws.com:5432/ccl
#    username: cupcakelearning
#    password: cupcakelearning
    url: jdbc:postgresql:ccl
    username: postgres
    password: postgres

